apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MONGODB_USERNAME: "bWFjdGFyZ3VleWUyMDAz"
  MONGODB_PASSWORD: "dmlMNTJ6Tk5ib1NZeE8wdA=="
  MONGODB_URL: "Y2x1c3RlcjAuYnkyNWtuby5tb25nb2RiLm5ldA=="
  MONGODB_NAME: ""
